Fixed ByteCodeClassLoader's NoClassDefFoundError
The ByteCodeClassLoader used the name of the .class file as the name of the class to load. This resulted in an error since the file name is not the same as the fully qualified name of the class. The loader does not specify the class name anymore.